### PR TITLE
chore: release changelog action

### PR DESCRIPTION
**Pull request by zaerald**

### CODE REVIEW

**Comment by Unthrottled** [comment]
@zaerald What's up with this? Should it go in or not?

**Comment by zaerald** [comment]
@Unthrottled I already forgot about this project 💀. I got demotivated and lost any idea on what features to add here. I got busy with security stuff too.

**Comment by Unthrottled** [comment]
🪦
Aight, I get that. 

I'll eventually swing around and make sure things get updated in time. I'll just add this to the list 👍

**Comment by zaerald** [comment]
Thanks for checking in @Unthrottled. Appreciate that, I'll get back to this project in a few months time. Right now, I have different interests that I like to work on.

**Comment by Unthrottled** [comment]
Yolo

**Pull request merged**
